version: '3.8'
services:
  qp-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: qp-server
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app
    env_file: ./.env